/* Generated by Yosys 0.46+124 (git sha1 8c2d1a16d, g++ 13.2.0-23ubuntu4 -fPIC -O3) */

module FA(a, b, cin, sum, cout);
  input a;
  wire a;
  input b;
  wire b;
  wire c1;
  wire c2;
  input cin;
  wire cin;
  output cout;
  wire cout;
  wire s1;
  output sum;
  wire sum;
  OR2_X1 _0_ (
    .A1(c1),
    .A2(c2),
    .ZN(cout)
  );
  HA M1 (
    .a(a),
    .b(b),
    .cout(c1),
    .sum(s1)
  );
  HA M2 (
    .a(s1),
    .b(cin),
    .cout(c2),
    .sum(sum)
  );
endmodule

module HA(a, b, sum, cout);
  input a;
  wire a;
  input b;
  wire b;
  output cout;
  wire cout;
  output sum;
  wire sum;
  AND2_X1 _0_ (
    .A1(a),
    .A2(b),
    .ZN(cout)
  );
  XOR2_X1 _1_ (
    .A(a),
    .B(b),
    .Z(sum)
  );
endmodule

module RCA16(a, b, cin, sum, cout);
  input [15:0] a;
  wire [15:0] a;
  input [15:0] b;
  wire [15:0] b;
  wire c1;
  input cin;
  wire cin;
  output cout;
  wire cout;
  output [15:0] sum;
  wire [15:0] sum;
  RCA8 A1 (
    .a(a[7:0]),
    .b(b[7:0]),
    .cin(cin),
    .cout(c1),
    .sum(sum[7:0])
  );
  RCA8 A2 (
    .a(a[15:8]),
    .b(b[15:8]),
    .cin(c1),
    .cout(cout),
    .sum(sum[15:8])
  );
endmodule

module RCA32(a, b, cin, sum, cout);
  input [31:0] a;
  wire [31:0] a;
  input [31:0] b;
  wire [31:0] b;
  wire c1;
  input cin;
  wire cin;
  output cout;
  wire cout;
  output [31:0] sum;
  wire [31:0] sum;
  RCA16 A1 (
    .a(a[15:0]),
    .b(b[15:0]),
    .cin(cin),
    .cout(c1),
    .sum(sum[15:0])
  );
  RCA16 A2 (
    .a(a[31:16]),
    .b(b[31:16]),
    .cin(cin),
    .cout(cout),
    .sum(sum[31:16])
  );
endmodule

module RCA4(a, b, cin, sum, cout);
  input [3:0] a;
  wire [3:0] a;
  input [3:0] b;
  wire [3:0] b;
  wire c1;
  wire c2;
  wire c3;
  input cin;
  wire cin;
  output cout;
  wire cout;
  output [3:0] sum;
  wire [3:0] sum;
  FA M1 (
    .a(a[0]),
    .b(b[0]),
    .cin(cin),
    .cout(c1),
    .sum(sum[0])
  );
  FA M2 (
    .a(a[1]),
    .b(b[1]),
    .cin(c1),
    .cout(c2),
    .sum(sum[1])
  );
  FA M3 (
    .a(a[2]),
    .b(b[2]),
    .cin(c2),
    .cout(c3),
    .sum(sum[2])
  );
  FA M4 (
    .a(a[3]),
    .b(b[3]),
    .cin(c3),
    .cout(cout),
    .sum(sum[3])
  );
endmodule

module RCA8(a, b, cin, sum, cout);
  input [7:0] a;
  wire [7:0] a;
  input [7:0] b;
  wire [7:0] b;
  wire c1;
  input cin;
  wire cin;
  output cout;
  wire cout;
  output [7:0] sum;
  wire [7:0] sum;
  RCA4 A1 (
    .a(a[3:0]),
    .b(b[3:0]),
    .cin(cin),
    .cout(c1),
    .sum(sum[3:0])
  );
  RCA4 A2 (
    .a(a[7:4]),
    .b(b[7:4]),
    .cin(c1),
    .cout(cout),
    .sum(sum[7:4])
  );
endmodule

module vedic16x16(A, B, Prod, ground, overflow);
  input [15:0] A;
  wire [15:0] A;
  input [15:0] B;
  wire [15:0] B;
  output [31:0] Prod;
  wire [31:0] Prod;
  wire c1;
  wire c2;
  wire c3;
  input ground;
  wire ground;
  output overflow;
  wire overflow;
  wire [15:0] s1;
  wire [15:0] s2;
  wire [15:0] v1;
  wire [15:0] v2;
  wire [15:0] v3;
  wire [15:0] v4;
  OR2_X1 _0_ (
    .A1(c1),
    .A2(c2),
    .ZN(c3)
  );
  RCA16 A1 (
    .a(v2),
    .b(v3),
    .cin(ground),
    .cout(c1),
    .sum(s1)
  );
  RCA16 A2 (
    .a(s1),
    .b({ ground, ground, ground, ground, ground, ground, ground, ground, v1[15:8] }),
    .cin(ground),
    .cout(c2),
    .sum(s2)
  );
  RCA16 A3 (
    .a(v4),
    .b({ ground, ground, ground, ground, ground, ground, ground, c3, s2[15:8] }),
    .cin(ground),
    .cout(overflow),
    .sum(Prod[31:16])
  );
  vedic8x8 V1 (
    .A(A[7:0]),
    .B(B[7:0]),
    .Prod(v1),
    .ground(ground)
  );
  vedic8x8 V2 (
    .A(A[15:8]),
    .B(B[7:0]),
    .Prod(v2),
    .ground(ground)
  );
  vedic8x8 V3 (
    .A(A[7:0]),
    .B(B[15:8]),
    .Prod(v3),
    .ground(ground)
  );
  vedic8x8 V4 (
    .A(A[15:8]),
    .B(B[15:8]),
    .Prod(v4),
    .ground(ground)
  );
  assign Prod[15:0] = { s2[7:0], v1[7:0] };
endmodule

module vedic2x2(A, B, Prod);
  input [1:0] A;
  wire [1:0] A;
  input [1:0] B;
  wire [1:0] B;
  output [3:0] Prod;
  wire [3:0] Prod;
  wire w1;
  wire w2;
  wire w3;
  wire w4;
  AND2_X1 _0_ (
    .A1(A[0]),
    .A2(B[0]),
    .ZN(Prod[0])
  );
  AND2_X1 _1_ (
    .A1(A[0]),
    .A2(B[1]),
    .ZN(w1)
  );
  AND2_X1 _2_ (
    .A1(B[0]),
    .A2(A[1]),
    .ZN(w2)
  );
  AND2_X1 _3_ (
    .A1(B[1]),
    .A2(A[1]),
    .ZN(w3)
  );
  HA HA1 (
    .a(w2),
    .b(w1),
    .cout(w4),
    .sum(Prod[1])
  );
  HA HA2 (
    .a(w4),
    .b(w3),
    .cout(Prod[3]),
    .sum(Prod[2])
  );
endmodule

module vedic32x32(A, B, Prod, ground, overflow);
  input [31:0] A;
  wire [31:0] A;
  input [31:0] B;
  wire [31:0] B;
  output [63:0] Prod;
  wire [63:0] Prod;
  wire c1;
  wire c2;
  wire c3;
  input ground;
  wire ground;
  output overflow;
  wire overflow;
  wire [31:0] s1;
  wire [31:0] s2;
  wire [31:0] v1;
  wire [31:0] v2;
  wire [31:0] v3;
  wire [31:0] v4;
  OR2_X1 _0_ (
    .A1(c1),
    .A2(c2),
    .ZN(c3)
  );
  RCA32 A1 (
    .a(v2),
    .b(v3),
    .cin(ground),
    .cout(c1),
    .sum(s1)
  );
  RCA32 A2 (
    .a(s1),
    .b({ ground, ground, ground, ground, ground, ground, ground, ground, ground, ground, ground, ground, ground, ground, ground, ground, v1[31:16] }),
    .cin(ground),
    .cout(c2),
    .sum(s2)
  );
  RCA32 A3 (
    .a(v4),
    .b({ ground, ground, ground, ground, ground, ground, ground, ground, ground, ground, ground, ground, ground, ground, ground, c3, s2[31:16] }),
    .cin(ground),
    .cout(overflow),
    .sum(Prod[63:32])
  );
  vedic16x16 V1 (
    .A(A[15:0]),
    .B(B[15:0]),
    .Prod(v1),
    .ground(ground)
  );
  vedic16x16 V2 (
    .A(A[31:16]),
    .B(B[15:0]),
    .Prod(v2),
    .ground(ground)
  );
  vedic16x16 V3 (
    .A(A[15:0]),
    .B(B[31:16]),
    .Prod(v3),
    .ground(ground)
  );
  vedic16x16 V4 (
    .A(A[31:16]),
    .B(B[31:16]),
    .Prod(v4),
    .ground(ground)
  );
  assign Prod[31:0] = { s2[15:0], v1[15:0] };
endmodule

module vedic4x4(A, B, Prod, ground, overflow);
  input [3:0] A;
  wire [3:0] A;
  input [3:0] B;
  wire [3:0] B;
  output [7:0] Prod;
  wire [7:0] Prod;
  wire c1;
  wire c2;
  wire c3;
  input ground;
  wire ground;
  output overflow;
  wire overflow;
  wire [3:0] s1;
  wire [3:0] s2;
  wire [3:0] v1;
  wire [3:0] v2;
  wire [3:0] v3;
  wire [3:0] v4;
  OR2_X1 _0_ (
    .A1(c1),
    .A2(c2),
    .ZN(c3)
  );
  RCA4 A1 (
    .a(v2),
    .b(v3),
    .cin(ground),
    .cout(c1),
    .sum(s1)
  );
  RCA4 A2 (
    .a(s1),
    .b({ ground, ground, v1[3:2] }),
    .cin(ground),
    .cout(c2),
    .sum(s2)
  );
  RCA4 A3 (
    .a(v4),
    .b({ ground, c3, s2[3:2] }),
    .cin(ground),
    .cout(overflow),
    .sum(Prod[7:4])
  );
  vedic2x2 V1 (
    .A(A[1:0]),
    .B(B[1:0]),
    .Prod(v1)
  );
  vedic2x2 V2 (
    .A(A[3:2]),
    .B(B[1:0]),
    .Prod(v2)
  );
  vedic2x2 V3 (
    .A(A[1:0]),
    .B(B[3:2]),
    .Prod(v3)
  );
  vedic2x2 V4 (
    .A(A[3:2]),
    .B(B[3:2]),
    .Prod(v4)
  );
  assign Prod[3:0] = { s2[1:0], v1[1:0] };
endmodule

module vedic8x8(A, B, Prod, ground, overflow);
  input [7:0] A;
  wire [7:0] A;
  input [7:0] B;
  wire [7:0] B;
  output [15:0] Prod;
  wire [15:0] Prod;
  wire c1;
  wire c2;
  wire c3;
  input ground;
  wire ground;
  output overflow;
  wire overflow;
  wire [7:0] s1;
  wire [7:0] s2;
  wire [7:0] v1;
  wire [7:0] v2;
  wire [7:0] v3;
  wire [7:0] v4;
  OR2_X1 _0_ (
    .A1(c1),
    .A2(c2),
    .ZN(c3)
  );
  RCA8 A1 (
    .a(v2),
    .b(v3),
    .cin(ground),
    .cout(c1),
    .sum(s1)
  );
  RCA8 A2 (
    .a(s1),
    .b({ ground, ground, ground, ground, v1[7:4] }),
    .cin(ground),
    .cout(c2),
    .sum(s2)
  );
  RCA8 A3 (
    .a(v4),
    .b({ ground, ground, ground, c3, s2[7:4] }),
    .cin(ground),
    .cout(overflow),
    .sum(Prod[15:8])
  );
  vedic4x4 V1 (
    .A(A[3:0]),
    .B(B[3:0]),
    .Prod(v1),
    .ground(ground)
  );
  vedic4x4 V2 (
    .A(A[7:4]),
    .B(B[3:0]),
    .Prod(v2),
    .ground(ground)
  );
  vedic4x4 V3 (
    .A(A[3:0]),
    .B(B[7:4]),
    .Prod(v3),
    .ground(ground)
  );
  vedic4x4 V4 (
    .A(A[7:4]),
    .B(B[7:4]),
    .Prod(v4),
    .ground(ground)
  );
  assign Prod[7:0] = { s2[3:0], v1[3:0] };
endmodule
